[package]
name = "treenity"
version = "0.1.0"
authors = ["Tigran Bayburtsyan <tigran@bayburtsyan.com>"]

[dependencies]
mio = "0.6.4"
log = "0.3"
num_cpus = "1.2.0"
slab = "0.3.0"
chrono = "0.3"
clap = "2.20.5"
threadpool = "1.3.2"